name: web-e2e

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build web
        run: pnpm -C apps/web build
      - name: Start web
        run: pnpm -C apps/web start &
      - name: Wait for web
        run: npx wait-on http://localhost:3000
      - name: Install Playwright Browsers
        run: pnpm -C apps/web exec playwright install --with-deps chromium
      - name: Run e2e tests
        run: pnpm -C apps/web e2e:ci
